name: newbie
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  intl: ^0.18.1
  google_fonts: ^6.1.0
  get_storage: ^2.1.1

  firebase_core: 2.16.0
  firebase_auth: 4.10.0
  cloud_firestore: ^4.9.2
  google_sign_in: ^6.1.5
  firebase_storage: ^11.2.7

  file_picker: ^5.5.0
  open_file: ^3.3.2
  image_picker: ^1.0.4
  uuid: ^3.0.5
  path_provider: ^2.1.1
  dio: ^5.3.3
  syncfusion_flutter_pdfviewer: ^23.1.36
  permission_handler: ^11.0.0
  # flutter_webview_plugin: ^0.4.0
  syncfusion_flutter_charts: ^23.1.38
  flutter_inappwebview: ^5.7.2+3
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
